### ISSUE TITLE
Breadcrumbs on Views?

### ISSUE THREAD

**Issue by brandex007** [Greg-Boggs/easy_breadcrumb#13]
The breadcrumbs work great and I appreciate the project! One problem I noticed is that views that are pages do not show breadcrumbs. Is this a feature that is being planned to work on?

**Comment by Greg-Boggs** [comment]
They should! Feel free to open an issue with more info over on D.O https://www.drupal.org/project/issues/easy_breadcrumb

**Comment by brandex007** [comment]
Great thanks.
